"use client";
import { useState } from "react";

function submitJson(url: string, payload: unknown) {
  return fetch(url, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) });
}

export function HealthProfileForm() { const [msg, setMsg] = useState(""); return <form className="space-y-2" onSubmit={async (e)=>{e.preventDefault(); const f=new FormData(e.currentTarget); await submitJson('/api/profile', Object.fromEntries(f.entries())); setMsg('已保存');}}><input name="name" placeholder="姓名或昵称" required/><input name="gender" placeholder="性别" required/><input name="birthYear" type="number" placeholder="出生年份" required/><input name="heightCm" type="number" step="0.1" placeholder="身高cm" required/><input name="weightKg" type="number" step="0.1" placeholder="体重kg" required/><input name="bloodType" placeholder="血型"/><input name="countryRegion" placeholder="国家/地区" required/><textarea name="allergies" placeholder="过敏史"/><textarea name="pastHistory" placeholder="既往病史"/><textarea name="familyHistory" placeholder="家族病史"/><textarea name="longTermMeds" placeholder="长期用药"/><textarea name="surgeries" placeholder="手术史"/><textarea name="notes" placeholder="备注"/><button className="bg-medical-500 text-white">保存档案</button><p>{msg}</p></form>; }

export function SymptomForm(){const [msg,setMsg]=useState(""); return <form className="space-y-2" onSubmit={async(e)=>{e.preventDefault(); const f=new FormData(e.currentTarget); await submitJson('/api/symptoms', Object.fromEntries(f.entries())); setMsg('已保存并生成AI风险提示');}}><input name="symptomName" placeholder="症状名称" required/><input type="datetime-local" name="startTime" required/><input name="duration" placeholder="持续时间" required/><input type="number" min={1} max={10} name="severity" placeholder="严重程度1-10" required/><input name="bodyPart" placeholder="部位"/><input name="triggers" placeholder="诱因"/><input name="associated" placeholder="伴随症状"/><select name="relieved"><option value="true">已缓解</option><option value="false">未缓解</option></select><textarea name="notes" placeholder="备注"/><button className="bg-medical-500 text-white">保存症状</button><p>{msg}</p></form>}

export function LifestyleForm(){const [msg,setMsg]=useState("");return <form className="space-y-2" onSubmit={async(e)=>{e.preventDefault();const f=new FormData(e.currentTarget); await submitJson('/api/lifestyle', Object.fromEntries(f.entries())); setMsg('已保存');}}><input name="sleepHours" type="number" step="0.1" placeholder="睡眠小时" required/><input name="diet" placeholder="饮食情况" required/><input name="waterIntakeL" type="number" step="0.1" placeholder="饮水量L" required/><input name="exercise" placeholder="运动情况" required/><input name="stressLevel" type="number" min={1} max={10} placeholder="情绪压力1-10" required/><input name="smokingAlcohol" placeholder="吸烟饮酒" required/><input name="caffeine" placeholder="咖啡因摄入" required/><textarea name="notes" placeholder="备注"/><button className="bg-medical-500 text-white">保存生活习惯</button><p>{msg}</p></form>}

export function RecordUploadForm(){const [msg,setMsg]=useState("");return <form className="space-y-2" onSubmit={async(e)=>{e.preventDefault();const f=new FormData(e.currentTarget); await fetch('/api/records',{method:'POST', body:f}); setMsg('已上传元信息');}}><input type="file" name="file" accept=".pdf,.jpg,.jpeg,.png" required/><input name="category" placeholder="报告类别" required/><input name="reportDate" type="date" required/><textarea name="note" placeholder="备注"/><button className="bg-medical-500 text-white">上传报告</button><p>{msg}</p></form>}

export function VisitPackPreview({ markdown }: { markdown: string }) { return <pre className="bg-white border rounded p-4 whitespace-pre-wrap">{markdown}</pre>; }
